apiVersion: v1
kind: Secret
metadata:
  name: student-project-secret
  namespace: student-project
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "postgres"